### ISSUE TITLE
대망의 테스트 결과화면 기능 구현

### ISSUE THREAD

**Issue by ohjiyun** [2021-SMHRD-IITP-Bigdata-2/nadeuli#18]
메인 여행지 지역 추천이 제일먼저 나오고
코로나 현황 데이터를 보여주고
서브 안심여행지 추천
안심 맛집 추천(데이터 가져온거 연결해서 보여주기)
안심 숙소 추천(사이트 연계)

- [x] 사용자가 입력한 테스트값 가져오기
- [x] 사용자가 입력한 테스트값이 들어간 것들을 or, like, group by, order by , count 등의 함수들을 이용해서 순서대로 가져오기
- [x] 코로나 상황 가져 오기
- [x] 코로나 상황이 사회적거리두기 3?4단계 이상일 경우 그 다음 우선지역 가져오기
- [x] 지역에 따른 안심숙소,식당,체험지 가져오기

**Comment by Inyoung1ee** [comment]
1차로 사용자의 테스트 결과를 sns 데이터에서 어떻게 빈도 분석을 해야 할 지 hr 서버 기존에 있던 테이블(employees)로 시행해보았습니다.
 
select manager_id ,count(*) as count
from employees
where manager_id like '1%' or manager_id like '2%'
group by manager_id
order by count desc;

위의 코드를 바탕으로 분석 로직을 구현하면 될 것 같습니다.
