### ISSUE TITLE
버튼 정리하기

### ISSUE THREAD

**Issue by Inyoung1ee** [2021-SMHRD-IITP-Bigdata-2/nadeuli#26]
- [x] 모든 페이지 버튼 정리하기(ex-> 클릭하면 제대로 이동하게 하기)
- [x] 로그인, 로그아웃 버튼 정리하기 (세션값 확인해서 로그인/로그아웃 버튼 바뀌게 하기)

**Comment by Hyunwook** [comment]
main.jsp, properties 버튼 정리
